# Attempt to add a badge to a given PR that will
# update coverage

name: generate-pr-coverage-badge

on:
  push:
    branches:
        - main
    paths-ignore:
      - README.md
      - FORK.md
      - AUTHORS.md
      - CHANGELOG.md
      - .gitignore
      - .github/**
      - _legacy/**
      - _examples/**
      - _assets/**
      - _test/**
      - LICENSE
      - Makefile
  pull_request:
    types: [opened]

env:
  GO_VER: 1.20.3

jobs:
  generate-pr-badge:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.GO_VER }}

    - name: Run tests
      run: go test --timeout=1m --coverprofile cover.out -v ./...
  
    - name: check test coverage
      id: coverage
      uses: vladopajic/go-test-coverage@v2
      with:       
        # Configure action by specifying input parameters individually (option 2)
        profile: cover.out
        local-prefix: github.com/asciifaceman/tooey
        # these thresholds are so low right now, we will improve
        threshold-file: 0
        threshold-package: 0
        threshold-total: 20

    - name: add badge in PR comment
      uses: actions/github-script@v6
      if: github.event.created
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: "![coverage](https://raw.githubusercontent.com/asciifaceman/tooey/badges/.badges/main/${{ github.event.number }}-coverage.svg)"
          })